### PR TITLE
Added Gradle wrapper jar

### PR DESCRIPTION
**Pull request by mrmike**
Right now it's not possible to use gradle wrapper in project. 

To fix this I've excluded wrapper jar file from `.gitignore` and added proper `gradle-wrapper.jar` to project.

### CODE REVIEW

**Comment by hzsweers** [comment]
Included wrapper works fine for me...?

**Comment by T12E** [comment]
Same problem for me, `gradlew` doesn't work.
```sh
$ ./gradlew app:assembleDebug
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by mrmike** [comment]
@T12E 
Have you tested it on my fork?

**Comment by mo** [comment]
The wrapper .jar is indeed missing and @mrmike's fixes the problem.

**Comment by hidroh** [comment]
:+1:

**Comment by jaredsburrows** [comment]
Simple add `gradle` to your `$PATH` and then use `gradle` instead.

I know this is a problem for this repository but at least you can easily work around it or run `gradle wrapper` and add your own.

**Pull request closed without merging**
