### PR TITLE
Add intellij idea and iml files to gitignore

### PR DESCRIPTION
**Pull request by caseykulm**
Just added this so that the repo won't show as modified when opened up in Android Studio.

### CODE REVIEW

**Comment by caseykulm** [comment]
Thanks for this project by the way. Really nice to see an app showcasing more than just 1 neat design element in use.

**Comment by seasonyuu** [comment]
It seems that the owner had given up this project

**Comment by jaredsburrows** [comment]
@seasonyuu Why don't you ask him? @chrisbanes

**Comment by jaredsburrows** [comment]
@caseykulm  +1

**Pull request closed without merging**
