### PR TITLE
Added missing Gradle wrapper jar, and updated gitignore

### PR DESCRIPTION
**Pull request by rafaeltoledo**
Probably due to *.jar being ignored by Git, the Gradle wrapper jar file is missing.

### CODE REVIEW

**Comment by jonalmeida** [comment]
If you force git to add gradle-wrapper once, you won't have to modify the gitignore file then.
```
git add --force gradle/wrapper/gradle-wrapper.jar
```

**Comment by rafaeltoledo** [comment]
I am not a huge fan of forced commands on Git. In this particular case, adding `!gradle-wrapper.jar` to .gitignore solves the problem (and works for the need of updating this file in future)

**Comment by FabianFrank** [comment]
+1

**Comment by czak** [comment]
I do agree the jar is missing. However, I don't think this PR is the correct way to solve this issue.
First, accepting an arbitrary jar file sounds like a bad idea overall. What version is it? Where does it come from?
Second, I don't think anything needs to be **added** to the `.gitignore`.

Instead, I would recommend simply **removing** the following lines from `.gitignore`:

```
# Package Files #
*.jar
*.war
*.ear
```

There's no good reason to have the above ignores for this project. And - as is apparent in this case - these catch-all clauses could hide what might actually be necessary.

After this change, @chrisbanes would need to `git add` the `gradle/wrapper/gradle-wrapper.jar`.

**Comment by tommai78101** [comment]
Hi to everyone,

Right now, what's the best way to handle `gradle-wrapper.jar` and related files?

**Pull request closed without merging**
