### PR TITLE
Add the drawertoggle

### PR DESCRIPTION
**Pull request by Jatra**
Useful to include drawer toggle for reference app

### CODE REVIEW

**Comment by brucewuu520** [comment]
on xiaomi devices, the toolbar and statusbar overlap,see the red line
img

**Comment by Simon-Raes** [comment]
Also happens on my devices. Removing "android:fitsSystemWindows="true"" from the CoordinatorLayout fixes the arrow position, but turns the status bar gray instead of purple.

**Comment by brucewuu520** [comment]
i found samsung device have the same problem

**Comment by santhoshvai** [comment]
My Moto e has the same problem

**Comment by Ydcool** [comment]
LG G2  +1

**Comment by helmifluida** [comment]
Zenfone 5 same problem

**Comment by PaulWoitaschek** [comment]
Nexus 5x, Android 6.0.1 stock, same problem. Why was this closed?

**Pull request closed without merging**
